#!/bin/bash
curl -XDELETE 'http://localhost:9200/notes'
echo
curl -XPOST 'http://localhost:9200/notes' -d '
{
    index:"notes",
    type: "document",
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "myAnalyzer" : {
                    "tokenizer" : "standard",
                    "filter" : ["asciifolding","lowercase","synonym","my_stop"]
                }
            },
            "filter" : {
                "synonym" : {
                    "type" : "synonym",
                    "synonyms_path" : "synonyms.txt"
                },
                "my_stop": {
                    "type":"stop",
                    "stopwords": ["el", "lo", "las","los", "a", "y"]
                }
            }
            
            }
        }
    },
    "mappings" : {
        "note": {
                "properties": {
                    "title": {
                                "type": "string",
                                "store" : "yes",
                                "index_analyzer" : "myAnalyzer"
                         },
                    "text": {
                                "type": "string",
                                "store" : "yes",
                                "index_analyzer" : "myAnalyzer"
                         }
                 }
            }
    }
    }'